/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTiming */

#ifndef _Included_NativeTiming
#define _Included_NativeTiming
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTiming
 * Method:    report_cpu_time
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_NativeTiming_report_1cpu_1time
  (JNIEnv *, jclass);

/*
 * Class:     NativeTiming
 * Method:    report_sys_time
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_NativeTiming_report_1sys_1time
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
